name: Test Snap Build

on:
  push:
    branches:
      - main
  workflow_dispatch: # or manually
    
jobs:
  publish_amd64:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: install snapcraft
      run: sudo snap install snapcraft --classic
    - name: build snap
      run: |
        sudo snapcraft --destructive-mode
        sudo rm -rf $HOME/.config/snapcraft
